---
date: 2017-04-10
section_name: 책소개
is_front_page: false
page_heading_margin_in_lines: 3
:ad_type: 5단통
page_columns: 7
grid_size:
- 146.99664257142857
- 97.322846
lines_per_grid: 7
width: 1114.0158780000002
height: 1544.88207
left_margin: 42.519690000000004
top_margin: 42.519690000000004
right_margin: 42.519690000000004
bottom_margin: 42.519690000000004
gutter: 12.755907
draw_divider: 
story_frames:
- - 0
  - 0
  - 4
  - 5
- - 4
  - 0
  - 3
  - 5
- - 0
  - 5
  - 4
  - 5
- - 4
  - 5
  - 3
  - 5
- - 0
  - 10
  - 7
  - 5
  - :광고: 5단통
article_line_thickness: 0.3
